name: just_audio
description: A feature-rich audio player for Flutter. Loop, clip and concatenate any sound from any source (asset/file/URL/stream) in a variety of audio formats with gapless playback.
version: 0.9.42
publish_to: none
homepage: https://ryanheise.github.io/just_audio
repository: https://github.com/ryanheise/just_audio/tree/minor/just_audio
issue_tracker: https://github.com/ryanheise/just_audio/issues
topics:
  - audio
  - sound
  - player
  - background

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  just_audio_platform_interface:
    git: https://github.com/kumsumit/just_audio_platform_interface.git
  # just_audio_platform_interface:
  #   path: ../just_audio_platform_interface
  just_audio_web: 
    git: https://github.com/kumsumit/just_audio_web.git
  # just_audio_web:
  #   path: ../just_audio_web
  audio_session:
    git: https://github.com/sumitsharansatsangi/audio_session.git
  rxdart: '>=0.26.0 <0.29.0'
  path: ^1.8.0
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  async: ^2.5.0
  uuid: '>=4.5.1 <5.0.0'
  crypto: ^3.0.0
  meta: ^1.11.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.just_audio
        pluginClass: JustAudioPlugin
      ios:
        pluginClass: JustAudioPlugin
      macos:
        pluginClass: JustAudioPlugin
      web:
        default_package: just_audio_web
